apiVersion: v1
kind: Deployment
metadata:
  name: admin-api
  labels:
    name: admin-api
spec:
  replicas: 1
  selectors:
    matchLabels:
      service: admin-api
  template:
    metadata:
      labels:
        service: admin-api
    spec:
      containers:
      - name: admin-api
        image: isjustintime/cd12355-admin-api:latest
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: admin-api
spec:
  selector:
    name: admin-api
  ports:
  - name: "5151"
    protocol: TCP
    port: 5151
    targetPort: 5151
