apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:
  selector:
    app.kubernetes.io/name: user-api
  ports:
  - name: "5152"
    protocol: TCP
    port: 5152
    targetPort: 5152
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user-api
  template:
    metadata:
      labels:
        service: user-api
    spec:
      containers:
      - name: user-api
        image: isjustintime/cd12355-user-api:latest
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      restartPolicy: Always
