apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
# The password should be retrieved from the deployment after the Helm Chart is applied
# export POSTGRES_PASSWORD=$(kubectl get secret --namespace default <RELEASE_NAME> -o jsonpath="{.data.postgres-password}" | base64 -d)  
  DB_PASSWORD: PASSWORD_HERE